x-minio-common: &minio-common
  image: quay.io/minio/minio:latest
  command: server --console-address ":9090" /minio1/mnt/data
  ports:
    - "9000:9000"
    - "9090:9090"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3
services:
  postgres:
    image: postgres:17.5-bookworm
    restart: unless-stopped
    env_file:
      - .env
    user: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - 127.0.0.1:5432:5432

  backend:
    build:
      context: backend/
      dockerfile: prod.Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      minio1:
        condition: service_healthy
    env_file:
      - backend/.env
    ports:
      - 8080:8080

  website:
    build:
      context: website/
      dockerfile: prod.Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - 3000:3000

  ml-server:
    build:
      context: ml/
      dockerfile: prod.Dockerfile
    restart: unless-stopped
    env_file:
      - ml/.env
    ports:
      - 50051:50051

  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - type: bind
        source: /mnt/data/compose
        target: /mnt/data
      - type: bind
        source: /etc/default/minio
        target: /etc/config.env

volumes:
  pgdata:
