services:
  postgres:
    image: postgres:17.5-bookworm
    restart: unless-stopped
    env_file:
      - .env
    user: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - 127.0.0.1:5432:5432

  backend:
    build:
      context: backend/
      dockerfile: prod.Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - backend/.env
    ports:
      - 8080:8080

  website:
    build:
      context: website/
      dockerfile: prod.Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - 3000:3000

  ml-server:
    build:
      context: ml/
      dockerfile: prod.Dockerfile
    restart: unless-stopped
    env_file:
      - ml/.env
    ports:
      - 50051:50051

volumes:
  pgdata:
