name: Backend Continuous integration

on:
  push:
    branches: [main, 3-create-ci-for-backend]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install protobuf compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Run cargo check
        run: |
          cd backend
          cargo check
          cd client-ext
          cargo check
          cd ..
          cd server-ext
          cargo check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install protobuf compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Run cargo test
        run: |
          cd backend
          cargo test
          cd client-ext
          cargo test
          cd ..
          cd server-ext
          cargo test

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install protobuf compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Run cargo fmt
        run: |
          cd backend
          cargo fmt --all -- --check
          cd client-ext
          cargo fmt --all -- --check
          cd ..
          cd server-ext
          cargo fmt --all -- --check

      - name: Run cargo clippy
        run: |
          cd backend
          cargo clippy --all-targets
          cd client-ext
          cargo clippy --all-targets
          cd ..
          cd server-ext
          cargo clippy --all-targets
