name: Changelog and Release

on: [ push, pull_request ]

jobs:
  changelog:
    name: Generate changelog and release
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Generate changelog
        id: git-cliff
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          version: latest
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit the CHANGELOG.md file
        if: github.event_name == 'push'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b temp-changelog
          git add CHANGELOG.md
          git commit -m "Renew changelog" || echo "No changes to commit"
          git push origin temp-changelog
          
      - name: Create Pull Request for changelog
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          commit-message: "Renew changelog"
          title: "Update CHANGELOG.md"
          body: "Automated changelog update"
          branch: "update-changelog-${{ github.event.pull_request.number }}"
          base: ${{ github.event.pull_request.head.ref }}