name: Continuous deployment to a single server

on: workflow_dispatch

jobs:
  single-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Test SSH connection
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" \
            ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "echo 'Connection successful!'"

      - name: Deploy project
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" \
            ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
              cd ${{ secrets.PROJECT_PATH }} && \
              git config pull.rebase true && \
              git fetch && \
              git pull && \
              git submodule update --init --force && \
              cd backend && \
              git submodule update --init --force && \
              cd server-ext && \
              git submodule update --init --force
              cd .. && \
              cd .. && \
              cd ml && \
              git submodule update --init --force
              cd server-ext && \
              git submodule update --init --force && \
              cd .. && \
              cd .. && \
              cd website && \
              git submodule update --init --force && \
              cd .. && \
              docker compose down && \
              docker compose build --pull && \
              docker compose up -d"
